"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var abortBucketWorm_1 = require("./abortBucketWorm");
Object.defineProperty(exports, "abortBucketWorm", { enumerable: true, get: function () { return abortBucketWorm_1.abortBucketWorm; } });
var completeBucketWorm_1 = require("./completeBucketWorm");
Object.defineProperty(exports, "completeBucketWorm", { enumerable: true, get: function () { return completeBucketWorm_1.completeBucketWorm; } });
var deleteBucket_1 = require("./deleteBucket");
Object.defineProperty(exports, "deleteBucket", { enumerable: true, get: function () { return deleteBucket_1.deleteBucket; } });
var deleteBucketCORS_1 = require("./deleteBucketCORS");
Object.defineProperty(exports, "deleteBucketCORS", { enumerable: true, get: function () { return deleteBucketCORS_1.deleteBucketCORS; } });
var deleteBucketEncryption_1 = require("./deleteBucketEncryption");
Object.defineProperty(exports, "deleteBucketEncryption", { enumerable: true, get: function () { return deleteBucketEncryption_1.deleteBucketEncryption; } });
var deleteBucketInventory_1 = require("./deleteBucketInventory");
Object.defineProperty(exports, "deleteBucketInventory", { enumerable: true, get: function () { return deleteBucketInventory_1.deleteBucketInventory; } });
var deleteBucketLifecycle_1 = require("./deleteBucketLifecycle");
Object.defineProperty(exports, "deleteBucketLifecycle", { enumerable: true, get: function () { return deleteBucketLifecycle_1.deleteBucketLifecycle; } });
var deleteBucketLogging_1 = require("./deleteBucketLogging");
Object.defineProperty(exports, "deleteBucketLogging", { enumerable: true, get: function () { return deleteBucketLogging_1.deleteBucketLogging; } });
var deleteBucketPolicy_1 = require("./deleteBucketPolicy");
Object.defineProperty(exports, "deleteBucketPolicy", { enumerable: true, get: function () { return deleteBucketPolicy_1.deleteBucketPolicy; } });
var deleteBucketReferer_1 = require("./deleteBucketReferer");
Object.defineProperty(exports, "deleteBucketReferer", { enumerable: true, get: function () { return deleteBucketReferer_1.deleteBucketReferer; } });
var deleteBucketTags_1 = require("./deleteBucketTags");
Object.defineProperty(exports, "deleteBucketTags", { enumerable: true, get: function () { return deleteBucketTags_1.deleteBucketTags; } });
var deleteBucketWebsite_1 = require("./deleteBucketWebsite");
Object.defineProperty(exports, "deleteBucketWebsite", { enumerable: true, get: function () { return deleteBucketWebsite_1.deleteBucketWebsite; } });
var extendBucketWorm_1 = require("./extendBucketWorm");
Object.defineProperty(exports, "extendBucketWorm", { enumerable: true, get: function () { return extendBucketWorm_1.extendBucketWorm; } });
var getBucketACL_1 = require("./getBucketACL");
Object.defineProperty(exports, "getBucketACL", { enumerable: true, get: function () { return getBucketACL_1.getBucketACL; } });
var getBucketCORS_1 = require("./getBucketCORS");
Object.defineProperty(exports, "getBucketCORS", { enumerable: true, get: function () { return getBucketCORS_1.getBucketCORS; } });
var getBucketEncryption_1 = require("./getBucketEncryption");
Object.defineProperty(exports, "getBucketEncryption", { enumerable: true, get: function () { return getBucketEncryption_1.getBucketEncryption; } });
var getBucketInfo_1 = require("./getBucketInfo");
Object.defineProperty(exports, "getBucketInfo", { enumerable: true, get: function () { return getBucketInfo_1.getBucketInfo; } });
var getBucketInventory_1 = require("./getBucketInventory");
Object.defineProperty(exports, "getBucketInventory", { enumerable: true, get: function () { return getBucketInventory_1.getBucketInventory; } });
var getBucketLifecycle_1 = require("./getBucketLifecycle");
Object.defineProperty(exports, "getBucketLifecycle", { enumerable: true, get: function () { return getBucketLifecycle_1.getBucketLifecycle; } });
var getBucketLocation_1 = require("./getBucketLocation");
Object.defineProperty(exports, "getBucketLocation", { enumerable: true, get: function () { return getBucketLocation_1.getBucketLocation; } });
var getBucketLogging_1 = require("./getBucketLogging");
Object.defineProperty(exports, "getBucketLogging", { enumerable: true, get: function () { return getBucketLogging_1.getBucketLogging; } });
var getBucketPolicy_1 = require("./getBucketPolicy");
Object.defineProperty(exports, "getBucketPolicy", { enumerable: true, get: function () { return getBucketPolicy_1.getBucketPolicy; } });
var getBucketReferer_1 = require("./getBucketReferer");
Object.defineProperty(exports, "getBucketReferer", { enumerable: true, get: function () { return getBucketReferer_1.getBucketReferer; } });
var getBucketRequestPayment_1 = require("./getBucketRequestPayment");
Object.defineProperty(exports, "getBucketRequestPayment", { enumerable: true, get: function () { return getBucketRequestPayment_1.getBucketRequestPayment; } });
var getBucketTags_1 = require("./getBucketTags");
Object.defineProperty(exports, "getBucketTags", { enumerable: true, get: function () { return getBucketTags_1.getBucketTags; } });
var getBucketVersioning_1 = require("./getBucketVersioning");
Object.defineProperty(exports, "getBucketVersioning", { enumerable: true, get: function () { return getBucketVersioning_1.getBucketVersioning; } });
var getBucketWebsite_1 = require("./getBucketWebsite");
Object.defineProperty(exports, "getBucketWebsite", { enumerable: true, get: function () { return getBucketWebsite_1.getBucketWebsite; } });
var getBucketWorm_1 = require("./getBucketWorm");
Object.defineProperty(exports, "getBucketWorm", { enumerable: true, get: function () { return getBucketWorm_1.getBucketWorm; } });
var initiateBucketWorm_1 = require("./initiateBucketWorm");
Object.defineProperty(exports, "initiateBucketWorm", { enumerable: true, get: function () { return initiateBucketWorm_1.initiateBucketWorm; } });
var listBucketInventory_1 = require("./listBucketInventory");
Object.defineProperty(exports, "listBucketInventory", { enumerable: true, get: function () { return listBucketInventory_1.listBucketInventory; } });
var listBuckets_1 = require("./listBuckets");
Object.defineProperty(exports, "listBuckets", { enumerable: true, get: function () { return listBuckets_1.listBuckets; } });
var putBucket_1 = require("./putBucket");
Object.defineProperty(exports, "putBucket", { enumerable: true, get: function () { return putBucket_1.putBucket; } });
var putBucketACL_1 = require("./putBucketACL");
Object.defineProperty(exports, "putBucketACL", { enumerable: true, get: function () { return putBucketACL_1.putBucketACL; } });
var putBucketCORS_1 = require("./putBucketCORS");
Object.defineProperty(exports, "putBucketCORS", { enumerable: true, get: function () { return putBucketCORS_1.putBucketCORS; } });
var putBucketEncryption_1 = require("./putBucketEncryption");
Object.defineProperty(exports, "putBucketEncryption", { enumerable: true, get: function () { return putBucketEncryption_1.putBucketEncryption; } });
var putBucketInventory_1 = require("./putBucketInventory");
Object.defineProperty(exports, "putBucketInventory", { enumerable: true, get: function () { return putBucketInventory_1.putBucketInventory; } });
var putBucketLifecycle_1 = require("./putBucketLifecycle");
Object.defineProperty(exports, "putBucketLifecycle", { enumerable: true, get: function () { return putBucketLifecycle_1.putBucketLifecycle; } });
var putBucketLogging_1 = require("./putBucketLogging");
Object.defineProperty(exports, "putBucketLogging", { enumerable: true, get: function () { return putBucketLogging_1.putBucketLogging; } });
var putBucketPolicy_1 = require("./putBucketPolicy");
Object.defineProperty(exports, "putBucketPolicy", { enumerable: true, get: function () { return putBucketPolicy_1.putBucketPolicy; } });
var putBucketReferer_1 = require("./putBucketReferer");
Object.defineProperty(exports, "putBucketReferer", { enumerable: true, get: function () { return putBucketReferer_1.putBucketReferer; } });
var putBucketRequestPayment_1 = require("./putBucketRequestPayment");
Object.defineProperty(exports, "putBucketRequestPayment", { enumerable: true, get: function () { return putBucketRequestPayment_1.putBucketRequestPayment; } });
var putBucketTags_1 = require("./putBucketTags");
Object.defineProperty(exports, "putBucketTags", { enumerable: true, get: function () { return putBucketTags_1.putBucketTags; } });
var putBucketVersioning_1 = require("./putBucketVersioning");
Object.defineProperty(exports, "putBucketVersioning", { enumerable: true, get: function () { return putBucketVersioning_1.putBucketVersioning; } });
var putBucketWebsite_1 = require("./putBucketWebsite");
Object.defineProperty(exports, "putBucketWebsite", { enumerable: true, get: function () { return putBucketWebsite_1.putBucketWebsite; } });
