import { deleteBucket } from './deleteBucket';
import { deleteBucketCORS } from './deleteBucketCORS';
import { deleteBucketEncryption } from './deleteBucketEncryption';
import { deleteBucketLifecycle } from './deleteBucketLifecycle';
import { deleteBucketLogging } from './deleteBucketLogging';
import { deleteBucketPolicy } from './deleteBucketPolicy';
import { deleteBucketReferer } from './deleteBucketReferer';
import { deleteBucketTags } from './deleteBucketTags';
import { deleteBucketWebsite } from './deleteBucketWebsite';
import { getBucketACL } from './getBucketACL';
import { getBucketCORS } from './getBucketCORS';
import { getBucketEncryption } from './getBucketEncryption';
import { getBucketInfo } from './getBucketInfo';
import { getBucketLifecycle } from './getBucketLifecycle';
import { getBucketLocation } from './getBucketLocation';
import { getBucketLogging } from './getBucketLogging';
import { getBucketPolicy } from './getBucketPolicy';
import { getBucketReferer } from './getBucketReferer';
import { getBucketRequestPayment } from './getBucketRequestPayment';
import { getBucketTags } from './getBucketTags';
import { getBucketVersioning } from './getBucketVersioning';
import { getBucketWebsite } from './getBucketWebsite';
import { listBuckets } from './listBuckets';
import { putBucket } from './putBucket';
import { putBucketACL } from './putBucketACL';
import { putBucketCORS } from './putBucketCORS';
import { putBucketEncryption } from './putBucketEncryption';
import { putBucketLifecycle } from './putBucketLifecycle';
import { putBucketLogging } from './putBucketLogging';
import { putBucketPolicy } from './putBucketPolicy';
import { putBucketReferer } from './putBucketReferer';
import { putBucketRequestPayment } from './putBucketRequestPayment';
import { putBucketTags } from './putBucketTags';
import { putBucketVersioning } from './putBucketVersioning';
import { putBucketWebsite } from './putBucketWebsite';
declare const _default: {
    deleteBucket: typeof deleteBucket;
    deleteBucketCORS: typeof deleteBucketCORS;
    deleteBucketEncryption: typeof deleteBucketEncryption;
    deleteBucketLifecycle: typeof deleteBucketLifecycle;
    deleteBucketLogging: typeof deleteBucketLogging;
    deleteBucketPolicy: typeof deleteBucketPolicy;
    deleteBucketReferer: typeof deleteBucketReferer;
    deleteBucketTags: typeof deleteBucketTags;
    deleteBucketWebsite: typeof deleteBucketWebsite;
    getBucketACL: typeof getBucketACL;
    getBucketCORS: typeof getBucketCORS;
    getBucketEncryption: typeof getBucketEncryption;
    getBucketInfo: typeof getBucketInfo;
    getBucketLifecycle: typeof getBucketLifecycle;
    getBucketLocation: typeof getBucketLocation;
    getBucketLogging: typeof getBucketLogging;
    getBucketPolicy: typeof getBucketPolicy;
    getBucketReferer: typeof getBucketReferer;
    getBucketRequestPayment: typeof getBucketRequestPayment;
    getBucketTags: typeof getBucketTags;
    getBucketVersioning: typeof getBucketVersioning;
    getBucketWebsite: typeof getBucketWebsite;
    listBuckets: typeof listBuckets;
    putBucket: typeof putBucket;
    putBucketACL: typeof putBucketACL;
    putBucketCORS: typeof putBucketCORS;
    putBucketEncryption: typeof putBucketEncryption;
    putBucketLifecycle: typeof putBucketLifecycle;
    putBucketLogging: typeof putBucketLogging;
    putBucketPolicy: typeof putBucketPolicy;
    putBucketReferer: typeof putBucketReferer;
    putBucketRequestPayment: typeof putBucketRequestPayment;
    putBucketTags: typeof putBucketTags;
    putBucketVersioning: typeof putBucketVersioning;
    putBucketWebsite: typeof putBucketWebsite;
};
export default _default;
