import { deleteBucketEncryption } from './deleteBucketEncryption';
import { deleteBucketLifecycle } from './deleteBucketLifecycle';
import { deleteBucketPolicy } from './deleteBucketPolicy';
import { deleteBucketTags } from './deleteBucketTags';
import { deleteBucketWebsite } from './deleteBucketWebsite';
import { getBucketEncryption } from './getBucketEncryption';
import { getBucketLifecycle } from './getBucketLifecycle';
import { getBucketPolicy } from './getBucketPolicy';
import { getBucketRequestPayment } from './getBucketRequestPayment';
import { getBucketTags } from './getBucketTags';
import { getBucketVersioning } from './getBucketVersioning';
import { getBucketWebsite } from './getBucketWebsite';
import { putBucket } from './putBucket';
import { putBucketEncryption } from './putBucketEncryption';
import { putBucketLifecycle } from './putBucketLifecycle';
import { putBucketPolicy } from './putBucketPolicy';
import { putBucketRequestPayment } from './putBucketRequestPayment';
import { putBucketTags } from './putBucketTags';
import { putBucketVersioning } from './putBucketVersioning';
import { putBucketWebsite } from './putBucketWebsite';
declare const _default: {
    deleteBucketEncryption: typeof deleteBucketEncryption;
    deleteBucketLifecycle: typeof deleteBucketLifecycle;
    deleteBucketPolicy: typeof deleteBucketPolicy;
    deleteBucketTags: typeof deleteBucketTags;
    deleteBucketWebsite: typeof deleteBucketWebsite;
    getBucketEncryption: typeof getBucketEncryption;
    getBucketLifecycle: typeof getBucketLifecycle;
    getBucketPolicy: typeof getBucketPolicy;
    getBucketRequestPayment: typeof getBucketRequestPayment;
    getBucketTags: typeof getBucketTags;
    getBucketVersioning: typeof getBucketVersioning;
    getBucketWebsite: typeof getBucketWebsite;
    putBucket: typeof putBucket;
    putBucketEncryption: typeof putBucketEncryption;
    putBucketLifecycle: typeof putBucketLifecycle;
    putBucketPolicy: typeof putBucketPolicy;
    putBucketRequestPayment: typeof putBucketRequestPayment;
    putBucketTags: typeof putBucketTags;
    putBucketVersioning: typeof putBucketVersioning;
    putBucketWebsite: typeof putBucketWebsite;
};
export default _default;
