"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.OSS = void 0;
const _unSupportBrowserTip_1 = require("../common/utils/_unSupportBrowserTip");
const setConfig_1 = require("../setConfig");
const version_1 = require("./version");
var object_1 = require("../common/object");
Object.defineProperty(exports, "append", { enumerable: true, get: function () { return object_1.append; } });
Object.defineProperty(exports, "calculatePostSignature", { enumerable: true, get: function () { return object_1.calculatePostSignature; } });
Object.defineProperty(exports, "copy", { enumerable: true, get: function () { return object_1.copy; } });
Object.defineProperty(exports, "delete", { enumerable: true, get: function () { return object_1.delete; } });
Object.defineProperty(exports, "deleteObject", { enumerable: true, get: function () { return object_1.deleteObject; } });
Object.defineProperty(exports, "deleteMulti", { enumerable: true, get: function () { return object_1.deleteMulti; } });
Object.defineProperty(exports, "deleteObjectTagging", { enumerable: true, get: function () { return object_1.deleteObjectTagging; } });
Object.defineProperty(exports, "generateObjectUrl", { enumerable: true, get: function () { return object_1.generateObjectUrl; } });
Object.defineProperty(exports, "get", { enumerable: true, get: function () { return object_1.get; } });
Object.defineProperty(exports, "getACL", { enumerable: true, get: function () { return object_1.getACL; } });
Object.defineProperty(exports, "getAsyncFetch", { enumerable: true, get: function () { return object_1.getAsyncFetch; } });
Object.defineProperty(exports, "getBucketVersions", { enumerable: true, get: function () { return object_1.getBucketVersions; } });
Object.defineProperty(exports, "listObjectVersions", { enumerable: true, get: function () { return object_1.listObjectVersions; } });
Object.defineProperty(exports, "getObjectMeta", { enumerable: true, get: function () { return object_1.getObjectMeta; } });
Object.defineProperty(exports, "getObjectTagging", { enumerable: true, get: function () { return object_1.getObjectTagging; } });
Object.defineProperty(exports, "getObjectUrl", { enumerable: true, get: function () { return object_1.getObjectUrl; } });
Object.defineProperty(exports, "getSymlink", { enumerable: true, get: function () { return object_1.getSymlink; } });
Object.defineProperty(exports, "head", { enumerable: true, get: function () { return object_1.head; } });
Object.defineProperty(exports, "list", { enumerable: true, get: function () { return object_1.list; } });
Object.defineProperty(exports, "listV2", { enumerable: true, get: function () { return object_1.listV2; } });
Object.defineProperty(exports, "postAsyncFetch", { enumerable: true, get: function () { return object_1.postAsyncFetch; } });
Object.defineProperty(exports, "putACL", { enumerable: true, get: function () { return object_1.putACL; } });
Object.defineProperty(exports, "putMeta", { enumerable: true, get: function () { return object_1.putMeta; } });
Object.defineProperty(exports, "putObjectTagging", { enumerable: true, get: function () { return object_1.putObjectTagging; } });
Object.defineProperty(exports, "putSymlink", { enumerable: true, get: function () { return object_1.putSymlink; } });
Object.defineProperty(exports, "restore", { enumerable: true, get: function () { return object_1.restore; } });
Object.defineProperty(exports, "signatureUrl", { enumerable: true, get: function () { return object_1.signatureUrl; } });
var image_1 = require("../common/image");
Object.defineProperty(exports, "processObjectSave", { enumerable: true, get: function () { return image_1.processObjectSave; } });
var multipart_1 = require("../common/multipart");
Object.defineProperty(exports, "completeMultipartUpload", { enumerable: true, get: function () { return multipart_1.completeMultipartUpload; } });
Object.defineProperty(exports, "initMultipartUpload", { enumerable: true, get: function () { return multipart_1.initMultipartUpload; } });
Object.defineProperty(exports, "listUploads", { enumerable: true, get: function () { return multipart_1.listUploads; } });
Object.defineProperty(exports, "listParts", { enumerable: true, get: function () { return multipart_1.listParts; } });
Object.defineProperty(exports, "abortMultipartUpload", { enumerable: true, get: function () { return multipart_1.abortMultipartUpload; } });
Object.defineProperty(exports, "multipartUploadCopy", { enumerable: true, get: function () { return multipart_1.multipartUploadCopy; } });
Object.defineProperty(exports, "uploadPartCopy", { enumerable: true, get: function () { return multipart_1.uploadPartCopy; } });
var bucket_1 = require("../common/bucket");
Object.defineProperty(exports, "abortBucketWorm", { enumerable: true, get: function () { return bucket_1.abortBucketWorm; } });
Object.defineProperty(exports, "completeBucketWorm", { enumerable: true, get: function () { return bucket_1.completeBucketWorm; } });
Object.defineProperty(exports, "deleteBucket", { enumerable: true, get: function () { return bucket_1.deleteBucket; } });
Object.defineProperty(exports, "deleteBucketCORS", { enumerable: true, get: function () { return bucket_1.deleteBucketCORS; } });
Object.defineProperty(exports, "deleteBucketEncryption", { enumerable: true, get: function () { return bucket_1.deleteBucketEncryption; } });
Object.defineProperty(exports, "deleteBucketInventory", { enumerable: true, get: function () { return bucket_1.deleteBucketInventory; } });
Object.defineProperty(exports, "deleteBucketLifecycle", { enumerable: true, get: function () { return bucket_1.deleteBucketLifecycle; } });
Object.defineProperty(exports, "deleteBucketLogging", { enumerable: true, get: function () { return bucket_1.deleteBucketLogging; } });
Object.defineProperty(exports, "deleteBucketPolicy", { enumerable: true, get: function () { return bucket_1.deleteBucketPolicy; } });
Object.defineProperty(exports, "deleteBucketReferer", { enumerable: true, get: function () { return bucket_1.deleteBucketReferer; } });
Object.defineProperty(exports, "deleteBucketTags", { enumerable: true, get: function () { return bucket_1.deleteBucketTags; } });
Object.defineProperty(exports, "deleteBucketWebsite", { enumerable: true, get: function () { return bucket_1.deleteBucketWebsite; } });
Object.defineProperty(exports, "extendBucketWorm", { enumerable: true, get: function () { return bucket_1.extendBucketWorm; } });
Object.defineProperty(exports, "getBucketACL", { enumerable: true, get: function () { return bucket_1.getBucketACL; } });
Object.defineProperty(exports, "getBucketCORS", { enumerable: true, get: function () { return bucket_1.getBucketCORS; } });
Object.defineProperty(exports, "getBucketEncryption", { enumerable: true, get: function () { return bucket_1.getBucketEncryption; } });
Object.defineProperty(exports, "getBucketInfo", { enumerable: true, get: function () { return bucket_1.getBucketInfo; } });
Object.defineProperty(exports, "getBucketInventory", { enumerable: true, get: function () { return bucket_1.getBucketInventory; } });
Object.defineProperty(exports, "getBucketLifecycle", { enumerable: true, get: function () { return bucket_1.getBucketLifecycle; } });
Object.defineProperty(exports, "getBucketLocation", { enumerable: true, get: function () { return bucket_1.getBucketLocation; } });
Object.defineProperty(exports, "getBucketLogging", { enumerable: true, get: function () { return bucket_1.getBucketLogging; } });
Object.defineProperty(exports, "getBucketPolicy", { enumerable: true, get: function () { return bucket_1.getBucketPolicy; } });
Object.defineProperty(exports, "getBucketReferer", { enumerable: true, get: function () { return bucket_1.getBucketReferer; } });
Object.defineProperty(exports, "getBucketRequestPayment", { enumerable: true, get: function () { return bucket_1.getBucketRequestPayment; } });
Object.defineProperty(exports, "getBucketTags", { enumerable: true, get: function () { return bucket_1.getBucketTags; } });
Object.defineProperty(exports, "getBucketVersioning", { enumerable: true, get: function () { return bucket_1.getBucketVersioning; } });
Object.defineProperty(exports, "getBucketWebsite", { enumerable: true, get: function () { return bucket_1.getBucketWebsite; } });
Object.defineProperty(exports, "getBucketWorm", { enumerable: true, get: function () { return bucket_1.getBucketWorm; } });
Object.defineProperty(exports, "initiateBucketWorm", { enumerable: true, get: function () { return bucket_1.initiateBucketWorm; } });
Object.defineProperty(exports, "listBucketInventory", { enumerable: true, get: function () { return bucket_1.listBucketInventory; } });
Object.defineProperty(exports, "listBuckets", { enumerable: true, get: function () { return bucket_1.listBuckets; } });
Object.defineProperty(exports, "putBucket", { enumerable: true, get: function () { return bucket_1.putBucket; } });
Object.defineProperty(exports, "putBucketACL", { enumerable: true, get: function () { return bucket_1.putBucketACL; } });
Object.defineProperty(exports, "putBucketCORS", { enumerable: true, get: function () { return bucket_1.putBucketCORS; } });
Object.defineProperty(exports, "putBucketEncryption", { enumerable: true, get: function () { return bucket_1.putBucketEncryption; } });
Object.defineProperty(exports, "putBucketInventory", { enumerable: true, get: function () { return bucket_1.putBucketInventory; } });
Object.defineProperty(exports, "putBucketLifecycle", { enumerable: true, get: function () { return bucket_1.putBucketLifecycle; } });
Object.defineProperty(exports, "putBucketLogging", { enumerable: true, get: function () { return bucket_1.putBucketLogging; } });
Object.defineProperty(exports, "putBucketPolicy", { enumerable: true, get: function () { return bucket_1.putBucketPolicy; } });
Object.defineProperty(exports, "putBucketReferer", { enumerable: true, get: function () { return bucket_1.putBucketReferer; } });
Object.defineProperty(exports, "putBucketRequestPayment", { enumerable: true, get: function () { return bucket_1.putBucketRequestPayment; } });
Object.defineProperty(exports, "putBucketTags", { enumerable: true, get: function () { return bucket_1.putBucketTags; } });
Object.defineProperty(exports, "putBucketVersioning", { enumerable: true, get: function () { return bucket_1.putBucketVersioning; } });
Object.defineProperty(exports, "putBucketWebsite", { enumerable: true, get: function () { return bucket_1.putBucketWebsite; } });
var client_1 = require("../common/client");
Object.defineProperty(exports, "isCancel", { enumerable: true, get: function () { return client_1.isCancel; } });
Object.defineProperty(exports, "resetCancelFlag", { enumerable: true, get: function () { return client_1.resetCancelFlag; } });
Object.defineProperty(exports, "setRegion", { enumerable: true, get: function () { return client_1.setRegion; } });
Object.defineProperty(exports, "setBucket", { enumerable: true, get: function () { return client_1.setBucket; } });
Object.defineProperty(exports, "useBucket", { enumerable: true, get: function () { return client_1.useBucket; } });
Object.defineProperty(exports, "setSLDEnabled", { enumerable: true, get: function () { return client_1.setSLDEnabled; } });
Object.defineProperty(exports, "signature", { enumerable: true, get: function () { return client_1.signature; } });
var object_2 = require("./object");
Object.defineProperty(exports, "putStream", { enumerable: true, get: function () { return object_2.putStream; } });
Object.defineProperty(exports, "put", { enumerable: true, get: function () { return object_2.put; } });
var multipart_2 = require("./multipart");
Object.defineProperty(exports, "multipartUpload", { enumerable: true, get: function () { return multipart_2.multipartUpload; } });
Object.defineProperty(exports, "uploadPart", { enumerable: true, get: function () { return multipart_2.uploadPart; } });
Object.defineProperty(exports, "cancel", { enumerable: true, get: function () { return multipart_2.cancel; } });
class OSS extends setConfig_1.Client {
    constructor(props, ctx) {
        _unSupportBrowserTip_1._unSupportBrowserTip();
        super(props, ctx);
    }
}
exports.OSS = OSS;
OSS.urllib = require('../../shims/xhr');
OSS.version = version_1.version;
__exportStar(require("../types"), exports);
