"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var append_1 = require("./append");
Object.defineProperty(exports, "append", { enumerable: true, get: function () { return append_1.append; } });
var calculatePostSignature_1 = require("./calculatePostSignature");
Object.defineProperty(exports, "calculatePostSignature", { enumerable: true, get: function () { return calculatePostSignature_1.calculatePostSignature; } });
var copy_1 = require("./copy");
Object.defineProperty(exports, "copy", { enumerable: true, get: function () { return copy_1.copy; } });
// 兼容旧版本 delete
var delete_1 = require("./delete");
Object.defineProperty(exports, "deleteObject", { enumerable: true, get: function () { return delete_1.deleteObject; } });
Object.defineProperty(exports, "delete", { enumerable: true, get: function () { return delete_1.deleteObject; } });
var deleteMulti_1 = require("./deleteMulti");
Object.defineProperty(exports, "deleteMulti", { enumerable: true, get: function () { return deleteMulti_1.deleteMulti; } });
var deleteObjectTagging_1 = require("./deleteObjectTagging");
Object.defineProperty(exports, "deleteObjectTagging", { enumerable: true, get: function () { return deleteObjectTagging_1.deleteObjectTagging; } });
var generateObjectUrl_1 = require("./generateObjectUrl");
Object.defineProperty(exports, "generateObjectUrl", { enumerable: true, get: function () { return generateObjectUrl_1.generateObjectUrl; } });
var get_1 = require("./get");
Object.defineProperty(exports, "get", { enumerable: true, get: function () { return get_1.get; } });
var getACL_1 = require("./getACL");
Object.defineProperty(exports, "getACL", { enumerable: true, get: function () { return getACL_1.getACL; } });
var getAsyncFetch_1 = require("./getAsyncFetch");
Object.defineProperty(exports, "getAsyncFetch", { enumerable: true, get: function () { return getAsyncFetch_1.getAsyncFetch; } });
// 兼容旧版本 listObjectVersions
var getBucketVersions_1 = require("./getBucketVersions");
Object.defineProperty(exports, "getBucketVersions", { enumerable: true, get: function () { return getBucketVersions_1.getBucketVersions; } });
Object.defineProperty(exports, "listObjectVersions", { enumerable: true, get: function () { return getBucketVersions_1.getBucketVersions; } });
var getObjectMeta_1 = require("./getObjectMeta");
Object.defineProperty(exports, "getObjectMeta", { enumerable: true, get: function () { return getObjectMeta_1.getObjectMeta; } });
var getObjectTagging_1 = require("./getObjectTagging");
Object.defineProperty(exports, "getObjectTagging", { enumerable: true, get: function () { return getObjectTagging_1.getObjectTagging; } });
var getObjectUrl_1 = require("./getObjectUrl");
Object.defineProperty(exports, "getObjectUrl", { enumerable: true, get: function () { return getObjectUrl_1.getObjectUrl; } });
var getSymlink_1 = require("./getSymlink");
Object.defineProperty(exports, "getSymlink", { enumerable: true, get: function () { return getSymlink_1.getSymlink; } });
var head_1 = require("./head");
Object.defineProperty(exports, "head", { enumerable: true, get: function () { return head_1.head; } });
var list_1 = require("./list");
Object.defineProperty(exports, "list", { enumerable: true, get: function () { return list_1.list; } });
var listV2_1 = require("./listV2");
Object.defineProperty(exports, "listV2", { enumerable: true, get: function () { return listV2_1.listV2; } });
var postAsyncFetch_1 = require("./postAsyncFetch");
Object.defineProperty(exports, "postAsyncFetch", { enumerable: true, get: function () { return postAsyncFetch_1.postAsyncFetch; } });
var putACL_1 = require("./putACL");
Object.defineProperty(exports, "putACL", { enumerable: true, get: function () { return putACL_1.putACL; } });
var putMeta_1 = require("./putMeta");
Object.defineProperty(exports, "putMeta", { enumerable: true, get: function () { return putMeta_1.putMeta; } });
var putObjectTagging_1 = require("./putObjectTagging");
Object.defineProperty(exports, "putObjectTagging", { enumerable: true, get: function () { return putObjectTagging_1.putObjectTagging; } });
var putSymlink_1 = require("./putSymlink");
Object.defineProperty(exports, "putSymlink", { enumerable: true, get: function () { return putSymlink_1.putSymlink; } });
var restore_1 = require("./restore");
Object.defineProperty(exports, "restore", { enumerable: true, get: function () { return restore_1.restore; } });
var signatureUrl_1 = require("./signatureUrl");
Object.defineProperty(exports, "signatureUrl", { enumerable: true, get: function () { return signatureUrl_1.signatureUrl; } });
