"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var isCancel_1 = require("./isCancel");
Object.defineProperty(exports, "isCancel", { enumerable: true, get: function () { return isCancel_1.isCancel; } });
var resetCancelFlag_1 = require("./resetCancelFlag");
Object.defineProperty(exports, "resetCancelFlag", { enumerable: true, get: function () { return resetCancelFlag_1.resetCancelFlag; } });
var getBucket_1 = require("./getBucket");
Object.defineProperty(exports, "getBucket", { enumerable: true, get: function () { return getBucket_1.getBucket; } });
var setBucket_1 = require("./setBucket");
Object.defineProperty(exports, "setBucket", { enumerable: true, get: function () { return setBucket_1.setBucket; } });
Object.defineProperty(exports, "useBucket", { enumerable: true, get: function () { return setBucket_1.setBucket; } });
var setRegion_1 = require("./setRegion");
Object.defineProperty(exports, "setRegion", { enumerable: true, get: function () { return setRegion_1.setRegion; } });
var setSLDEnabled_1 = require("./setSLDEnabled");
Object.defineProperty(exports, "setSLDEnabled", { enumerable: true, get: function () { return setSLDEnabled_1.setSLDEnabled; } });
var signature_1 = require("./signature");
Object.defineProperty(exports, "signature", { enumerable: true, get: function () { return signature_1.signature; } });
