# Regularly clean test buckets at GMT 01:00 every day.
name: 'Schdule Delete'

on:
  schedule:
    - cron: '0 1 1/1 * *'

jobs:
  cleanAllBucket:
    environment: ali_oss_AK
    runs-on: ubuntu-latest

    env:
      ONCI: true
      ALI_SDK_OSS_ID: ${{secrets.ALI_SDK_OSS_ID}}
      ALI_SDK_OSS_SECRET: ${{secrets.ALI_SDK_OSS_SECRET}}
      ALI_SDK_OSS_REGION: ${{secrets.ALI_SDK_OSS_REGION}}
      ALI_SDK_STS_BUCKET: ${{secrets.ALI_SDK_STS_BUCKET}}
      ALI_SDK_STS_ID: ${{secrets.ALI_SDK_STS_ID}}
      ALI_SDK_STS_REGION: ${{secrets.ALI_SDK_STS_REGION}}
      ALI_SDK_STS_ROLE: ${{secrets.ALI_SDK_STS_ROLE}}
      ALI_SDK_STS_SECRET: ${{secrets.ALI_SDK_STS_SECRET}}

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v4
      - name: clean all bucket
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: x64
      - run: npm install
      - run: node test/node/fixtures/cleanAllBucket.js
